Default to publish an introspection document. WIP
TODO:
  * stringify-lisp-name isn't available in DEFINE-DBUS-METHOD
  * cache XML document (but *ALL-DBUS-OBJECTS* has no space for that??)
  * strange problem with the error message:
      # qdbus  org.adeht.publish-example / org.adeht.MyService.MyMethod
      Error: org.adeht.MyService.Error.MissingHandler
      Missing method-call handler at path / interface org.adeht.MyService name MyMethod
      # qdbus  org.adeht.publish-example / org.adeht.MyService.Mymethod a b
      Error: org.adeht.MyService.Error.MissingHandler
      Missing method-call handler at path / interface org.adeht.MyService name Mymethod
      # qdbus  org.adeht.publish-example / org.adeht.MyService.MyMethod a b
      Cannot find 'org.adeht.MyService.MyMethod' in object / at my.test.here
    case-sensitive only when correct arguments?